# Generated by Django 2.2.16 on 2022-02-05 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220204_1908'),
        ('reviews', '0004_auto_20220203_2148'),
    ]

    operations = [
    ]
