# Generated by Django 2.2.16 on 2022-02-02 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre_title',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='genre_title',
            old_name='title',
            new_name='title_id',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='category',
            new_name='category_id',
        ),
    ]
